<?

// filename:  dailyFruit.php
// loaded on home page as part of the default -- (#6)
// A random fruit is generated by $dailyFruit = $fruits->getDailyFruit();
// The random fruit id is passed in:  $views->getViews("views/dailyFruit.php", $dailyFruit);

//var_dump($results);

?>

<div class='container'>

	<div class="thumbnail col-md-4 col-md-offset-4">
	<h3>Daily Fruit</h3>



	<?
	foreach($results as $fruit){
	    echo "<p>Fruit: " . $fruit["fruitname"] . "</p>";
	    echo "<p>Color: " . $fruit["fruitcolor"] . "</p>";
	    echo '<img src="' . $fruit["fruitimage"] . '"/>';
	    echo"</br>";
	}
	?>
	</div><!-- closes thumbnail -->


</div><!-- closes container -->