# Site settings
title: My Awesome Template
email: krhodes26.2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/my_awesome_template" # the subpath of your site, e.g. /blog/
url: "/my_awesome_template" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
