{ "_id" : "Battleship", "name" : "Battleship", "type" : "product", "vendor" : "Mattel", "category" : "games", "features" : [ "All Ages Friendly" ] }
{ "_id" : "Malibu_Barbi", "name" : "Malibu Barbi", "type" : "product", "vendor" : "Mattel", "category" : "doll", "features" : [ "Dye Free", "Ages 2+" ] }
{ "_id" : "Mattel", "name" : "Mattel", "type" : "vendor", "address" : "763 Runies Ct", "city" : "El Segundo", "state" : "CA", "ll" : [ -118.416465, 33.91918 ], "phone" : [ { "type" : "main", "number" : "888-0=298-1236" }, { "type" : "Cust Serv", "number" : "445-332-9987" } ] }
{ "_id" : "Nintendo", "name" : "Nintendo", "type" : "vendor", "address" : "763 Runies Ct", "city" : "Redmond", "state" : "WA", "ll" : [ -122.121512, 47.673988 ], "phone" : [ { "type" : "main", "number" : "867-345-7782" }, { "type" : "Cust Serv", "number" : "334-929-9000" } ] }
{ "_id" : "PS3", "name" : "PS3", "type" : "product", "vendor" : "Sony", "category" : "electronics", "features" : [ "HD", "7.1 Surround Sound", "WiFi" ] }
{ "_id" : "Power_Glove", "name" : "Power Glove", "type" : "product", "vendor" : "Nintendo", "category" : "electronics", "features" : [ "One Size Fits All" ] }
{ "_id" : "Sony", "name" : "Sony", "type" : "vendor", "address" : "3213 Tech Way", "city" : "Los Angeles", "state" : "CA", "ll" : [ -118.243685, 34.052234 ], "phone" : [ { "type" : "main", "number" : "782-298-5638" }, { "type" : "fax", "number" : "321-829-9039" } ] }
{ "_id" : "Vaio", "name" : "Vaio", "type" : "product", "vendor" : "Sony", "category" : "electronics", "features" : [ "HD", "500m SSD", "WiFi" ] }
{ "_id" : "Wii", "name" : "Wii", "type" : "product", "vendor" : "Nintendo", "category" : "electronics", "features" : [ "Portable", "Water Resistent" ] }
{ "_id" : "McDonalds", "name" : "McDonalds","type" : "vendor","address" : "2111 McDonald's Dr","city" : "Oak Brook","state" : "IL","ll" : [ -87.944913, 41.847618 ],"phone" : [ { "type" : "main", "number" : "800-244-6227" },{ "type" : "fax", "number" : "562-822-9939" }] }
{ "_id" : "BigMac", "name" : "Big Mac", "type" : "product", "vendor" : "McDonalds", "category" : "fast food", "features" : [ "Special Sauce" ] }
{ "_id" : "ChickenNugget", "name" : "Chicken Nugget", "type" : "product", "vendor" : "McDonalds", "category" : "fast food", "features" : [ "Real White Meat" ] }
{ "_id" : "Reebok","name" : "Reebok","type" : "vendor","address" : "1895 J.W. Foster Boulevard","city" : "Canton","state" : "mA","ll" : [ -71.1263945, 42.206283 ],"phone" : [ { "type" : "main", "number" : "781-401-5000" }, { "type" : "fax", "number" : "781-401-7402" } ]}
{ "_id" : "ZpumpFusion", "name" : "ZPUMP FUSION", "type" : "product", "vendor" : "Reebok", "category" : "shoes", "features" : [ "Pump Technology" ] }