# Site settings
title: Pig Floyds
description: > # this means to ignore newlines until "baseurl:"
  Pig Floyds Urban Barbakoa in Orlando, FL is an international barbakoa restaurant specializing in smoked meats with distinct flavors.
baseurl: "/pig_floyds" # the subpath of your site, e.g. /blog/
url: "/pig_floyds" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
